apiVersion: litellm.m.crossplane.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: litellm-sit
spec:
  credentials:
    source: Secret
    secretRef:
      name: litellm-sit-creds
      namespace: crossplane-system
      key: credentials
