apiVersion: litellm.m.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: litellm-sit
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      name: litellm-sit-creds
      namespace: crossplane-system
      key: credentials
